# Generated by Django 5.1 on 2024-09-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='new_expiry_date',
            field=models.DateField(verbose_name='Дата истечения отметки Новый'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.PositiveIntegerField(help_text='в сомах', verbose_name='Цена товара'),
        ),
    ]
