# Generated by Django 5.1 on 2024-10-02 12:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_alter_productgallery_product_userfavoriteproduct'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='user_favorite_product',
            field=models.ManyToManyField(null=True, related_name='favorite_products', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='UserFavoriteProduct',
        ),
    ]
