# Generated by Django 5.1 on 2024-10-02 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_user_favorite_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='user_favorite_product',
        ),
    ]
