# Generated by Django 5.1 on 2024-09-06 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(upload_to='product_previews_images/', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='image',
            field=models.ImageField(upload_to='product_gallery', verbose_name='Изображение'),
        ),
    ]
