# Generated by Django 5.1 on 2024-09-20 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_productuserrating_delete_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuserrating',
            name='comment',
            field=models.TextField(null=True),
        ),
    ]
