# Generated by Django 5.1 on 2024-09-19 03:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_productuserrating_delete_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuserrating',
            name='comment',
            field=models.TextField(null=True, verbose_name='Обзор'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='market.product', verbose_name='Товар'),
        ),
    ]
