# Generated by Django 5.1 on 2024-09-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0008_productuserrating_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='productuserrating',
            name='phone',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
